FROM registry.cn-hangzhou.aliyuncs.com/alinux/alinux3

RUN yum -y install systemd
RUN yum -y groupinstall 'Development Tools'
RUN yum -y install \
ocaml \
ocaml-ocamlbuild \
wget \
python2 \
openssl-devel \
git \
openssl-devel \
libcurl-devel \
protobuf-devel \
cmake \
rpm-build \
createrepo \
yum-utils \
openssl-devel \
libcurl-devel \
protobuf-devel \
vim \
tree \
dos2unix \
git-lfs \
numactl-libs \
numactl-devel \
numactl \
pkgconf \
boost-devel \
protobuf-lite-devel \
protobuf-c-compiler \
protobuf-c-devel
RUN alternatives --set python /usr/bin/python2

RUN cd /root && git clone https://github.com/intel/linux-sgx.git; \
cd /root/linux-sgx; \
make preparation; \
make sdk_install_pkg; \
echo yes | /root/linux-sgx/linux/installer/bin/sgx_linux_x64_sdk_*.bin; \
source /root/linux-sgx/sgxsdk/environment; \
make rpm_local_repo

RUN yum -y install yum-utils; \
yum-config-manager --add-repo file:////root/linux-sgx/linux/installer/rpm/sgx_rpm_local_repo; \
yum install -y --setopt=install_weak_deps=False --nogpgcheck sgx-dcap-pccs.x86_64 tdx-qgs libsgx-dcap-default-qpl

RUN cd /root && git clone https://github.com/jialez0/SGXDataCenterAttestationPrimitives.git; \
cd /root/SGXDataCenterAttestationPrimitives/QuoteGeneration/quote_wrapper/qgs; \
source /root/linux-sgx/sgxsdk/environment; \
make clean && make && cp qgs /usr/local/bin/

RUN rm -rf /etc/sgx_default_qcnl.conf; \
touch /etc/sgx_default_qcnl.conf; \
echo '{\n\
    "pccs_url": "https://localhost:8081/sgx/certification/v4/",\n\
    "use_secure_cert": false,\n\
    "retry_times": 6,\n\
    "retry_delay": 10,\n\
    "pck_cache_expire_hours": 168\n\
}' >> /etc/sgx_default_qcnl.conf